<?php

namespace App\Repository;

/**
 * XLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
